name: PolyEvents
version: '${version}'
main: ci.polyevents.PolyEvents

api-version: 1.19
authors: [ MrSpaar ]
description: Plugin de gestion d'évènements
website: https://github.com/MrSpaar

commands:
  events:
    description: Gérer des évènements
    usage: /<command> [join/leave/list/...]
